spring:
  application:
    name: patient-service
  profiles:
    active: dev

server:
  port: 8083

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/application.log

  logback:
    rollingpolicy:
      total-size-cap: 100MB
      max-history: 7
      max-file-size: 10MB

jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: myclient